apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline-service
spec: 
  selector:
    matchLabels: 
      app: timeline-service
  replicas: 1
  template:
    metadata:
      labels:
        app: timeline-service
    spec:
      containers:
        - name: timeline-service
          image: florinpana01/tradetreasure-timeline-service-repository
          ports:
            - containerPort: 8000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: timeline-service-db-secret
                  key: timelinename
            - name: DB_PASS
              valueFrom: 
                secretKeyRef:
                  name: timeline-service-db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: timeline-service-db-secret
                  key: database
