name : Timeline Service

on: 
  push:
    branches:   
    - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install
        run: npm i
      - name: Test
        run: npm test
  build:
    needs: [tests]
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
         context: ./
         push: true
         tags: florinpana01/tradetreasure-timeline-service-repository
  deploy:
    needs: [build]
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
         credentials_json: ${{ secrets.GOOGLE_KUBERNETES_SERVICE_ACCOUNT }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - run: |-
        gcloud components install gke-gcloud-auth-plugin
        gcloud components update
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials tradetreasure-autopilot-cluster-1 --region europe-west1 --project praxis-bond-405913
      
    - name: Deploy
      run: |-
        cd k8s
        kubectl apply -f deployment.yaml